### ISSUE TITLE
Create User Test failures

### ISSUE THREAD

**Issue by jubrad** [MaterializeInc/rust-frontegg#11]
The tests seem to fail 
the following is from 

[`assert_eq!(created_user.name, name);` ](https://github.com/MaterializeInc/rust-frontegg/blob/main/tests/api.rs#L142)

```
test test_tenants_and_users ... FAILED

failures:

---- test_tenants_and_users stdout ----
thread 'test_tenants_and_users' panicked at 'assertion failed: `(left == right)`
  left: `"frontegg-test-0-0@example.com"`,
 right: `"user-0-0"`: create user name != user name', tests/api.rs:142:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I added some print statements to the create_user function. This is unexpected. 
```
UserRequest { tenant_id: 8191882a-76ac-4df7-89d3-53d4e74e4dc0, name: "user-0-0", email: "frontegg-test-0-0@example.com", metadata: Null, skip_invite_email: true }
CreatedUser { id: 35b5a3f0-646e-4216-8696-18a3a0baa328, name: "frontegg-test-0-0@example.com", email: "frontegg-test-0-0@example.com", metadata: Null, roles:... }

```

**Comment by benesch** [comment]
@jubrad can you report this upstream in our shared Slack channel with them? This seems like a straight bug in their API code that we should get them to fix. 

It'd be useful to investigate whether the v2 create user endpoint has the same bug. The v1 endpoint is deprecated, after all. If I recall correctly, though, there's a slight difference in behavior that's caused us to stick with the v1 endpoint. Something like the v2 endpoint requires you to generate your own user IDs, or something like that. I forget.

**Comment by jubrad** [comment]
https://materializeinc.slack.com/archives/C02940WNMRQ/p1687793341368209

Yeah this isn't hurting us at the moment I could look into migration to v2 api, but I don't think I'd get to that very soon.

**Comment by benesch** [comment]
Hm, I can't reproduce this. The tests pass just fine for me locally on `main`. Maybe it's something about the Frontegg workspace that you're using?!

**Comment by jubrad** [comment]
seems to have resolved itself?
